# Video Capturing

In [9]:
import numpy as np
import cv2 as cv
import os
import PIL as ImageGrab
import pyautogui as py
import keyboard
import time
import os


Collect the data

In [81]:

def capture_screenshots(num_screenshots, delay=1, save_dir="screenshots"):
    # Create the directory if it doesn't exist
    if not os.path.exists(save_dir):
        os.makedirs(save_dir)
    
    for i in range(num_screenshots):
        # Capture screenshot
        screenshot = py.screenshot(region=(5,30, 847, 542))
        
        # Save the screenshot to the specified directory with a unique filename
        save_path = os.path.join(save_dir, f'screenshot_{i+1}.png')
        screenshot.save(save_path)
        
        print(f'Screenshot {i+1} saved at {save_path}')
        
        # Add delay between screenshots
        time.sleep(delay)
    
    print(f"{num_screenshots} screenshots captured and saved in {save_dir}!")

# Example: Take 10 screenshots with a 1-second delay between each, store them in "my_game_screenshots" directory
capture_screenshots(50, delay=1, save_dir="my_game_screenshots")

Screenshot 1 saved at my_game_screenshots\screenshot_1.png
Screenshot 2 saved at my_game_screenshots\screenshot_2.png
Screenshot 3 saved at my_game_screenshots\screenshot_3.png
Screenshot 4 saved at my_game_screenshots\screenshot_4.png
Screenshot 5 saved at my_game_screenshots\screenshot_5.png
Screenshot 6 saved at my_game_screenshots\screenshot_6.png
Screenshot 7 saved at my_game_screenshots\screenshot_7.png
Screenshot 8 saved at my_game_screenshots\screenshot_8.png
Screenshot 9 saved at my_game_screenshots\screenshot_9.png
Screenshot 10 saved at my_game_screenshots\screenshot_10.png
Screenshot 11 saved at my_game_screenshots\screenshot_11.png
Screenshot 12 saved at my_game_screenshots\screenshot_12.png
Screenshot 13 saved at my_game_screenshots\screenshot_13.png
Screenshot 14 saved at my_game_screenshots\screenshot_14.png
Screenshot 15 saved at my_game_screenshots\screenshot_15.png
Screenshot 16 saved at my_game_screenshots\screenshot_16.png
Screenshot 17 saved at my_game_screenshots

# Image Processing

In [6]:
def takeSS():
    im = py.screenshot('image.png',region=(5,30, 847, 542))
    # Change the format that OpenCV can understand
    img = np.array(im)
    img_cvt = cv.cvtColor(img, cv.COLOR_RGB2BGR)

    # cv.imshow("das", img_cvt)
    # cv.waitKey(0)
    # cv.destroyAllWindows()
    return img_cvt

takeSS()


array([[[ 32,  32,  32],
        [ 32,  32,  32],
        [ 32,  32,  32],
        ...,
        [ 32,  32,  32],
        [ 32,  32,  32],
        [ 32,  32,  32]],

       [[ 32,  32,  32],
        [ 32,  32,  32],
        [ 32,  32,  32],
        ...,
        [ 32,  32,  32],
        [ 32,  32,  32],
        [ 32,  32,  32]],

       [[ 32,  32,  32],
        [ 32,  32,  32],
        [ 32,  32,  32],
        ...,
        [ 32,  32,  32],
        [ 32,  32,  32],
        [ 32,  32,  32]],

       ...,

       [[ 59,  59,  59],
        [ 59,  59,  59],
        [ 59,  59,  59],
        ...,
        [250, 250, 249],
        [250, 250, 249],
        [250, 250, 249]],

       [[ 59,  59,  59],
        [ 59,  59,  59],
        [ 59,  59,  59],
        ...,
        [250, 250, 249],
        [250, 250, 249],
        [250, 250, 249]],

       [[ 59,  59,  59],
        [ 59,  59,  59],
        [ 59,  59,  59],
        ...,
        [250, 250, 249],
        [250, 250, 249],
        [250, 250, 249]]

Simple threshold for segmentation

In [4]:
img = cv.imread('D:/Thinkin in programming/Metopen/image.png', cv.IMREAD_GRAYSCALE)
_, binary_image = cv.threshold(img, 127, 255, cv.THRESH_BINARY)

cv.imshow('img',img)
cv.waitKey(0)
cv.imshow('global threshold',binary_image)

cv.waitKey(0)
cv.destroyAllWindows()

Edge detection using Canny Edge Detection 

In [7]:
def canny_edge_detection(img_cvt):
    gray = cv.cvtColor(img_cvt, cv.COLOR_BGR2GRAY )
    kernel = 5
    blur = cv.GaussianBlur(gray, (kernel, kernel),0)
    canny = cv.Canny(blur, 50, 150)
    return canny

img = takeSS()
can = canny_edge_detection(img)

# cv.imwrite("canny.jpg",can)

cv.imshow("can", can)
cv.waitKey(0)
cv.destroyAllWindows()

Specify the region of interest

In [70]:
def roi(img):
    height = img.shape[0]
    width = img.shape[1]
    
    # Road mask
    mask = np.zeros_like(img)
    car_mask = np.zeros_like(img)
    
    # Define the coordinates for the trapezoid region
    # Adjust these points based on the shape of the lane and the car's position
    roi_points = np.array([
    [((250), (250)),    # Top-left corner
     ((600), (250)),    # Top-right corner     
     ((800), (300)),    # Bottom-right corner
     ((50),  (300))]    # Bottom-left corner    
    ], np.int32)

     # HARDCODE
    # triangle = np.array([
    # car_triangle = np.array([
    #     [(int(width * 0.1), height),  # Bottom-left point
    #      (int(width * 0.5), int(height * 0.5)),  # Top-middle point
    #      (int(width * 0.9), height)]  # Bottom-right point
    # ], np.int32)

    # Fill the triangular region
    cv.fillPoly(mask, roi_points, 255)
    #cv.fillPoly(mask, [car_triangle],0)
    
    # Use bitwise_and to apply the mask
    masked_image = cv.bitwise_and(img, mask)
    
    cv.imshow("ROI Applied", masked_image)
    cv.waitKey(0)
    cv.destroyAllWindows()
    
    return masked_image

#Example usage:
img_cvt = takeSS()  # Capture screenshot and convert
edges = canny_edge_detection(img_cvt)  # Perform Canny edge detection
masked_image = roi(edges)

cv.imwrite("Roi_img.jpg", masked_image)
cv.imshow("Masked Image", masked_image)
cv.waitKey(0)
cv.destroyAllWindows()

# For future adjustment, use trapezoid instead of triangle

In [8]:
def draw_road_roi(img):
    height, width = img.shape[0], img.shape[1]

    # Define a triangle that captures the road area in front of the car
    # triangle = np.array([
    #     [(int(width * 0.1), height),           # Bottom-left: 10% from the left of the frame
    #      (int(width * 0.5), int(height * 0.6)), # Top-middle: center of the frame, 60% up
    #      (int(width * 1.2), height)]           # Bottom-right: 90% from the left of the frame
    # ], np.int32)
    # HARDCODE
    roi_points = np.array([
    [((250), (250)),    # Top-left corner
     ((600), (250)),    # Top-right corner     
     ((800), (300)),    # Bottom-right corner
     ((50),  (300))]    # Bottom-left corner    
    ], np.int32)



    # Draw the triangle on the image for visualization
    cv.polylines(img, [roi_points], isClosed=True, color=(0, 255, 0), thickness=2)
    return img

# Example usage:
img_cvt = takeSS()  # Capture screenshot and convert
img_with_triangle = draw_road_roi(img_cvt)


cv.imshow("Road Roi", img_with_triangle)
cv.waitKey(0)
cv.destroyAllWindows()

Coordinate Explanation:
* (int(width * 0.1), height) defines the bottom-left point of the triangle (10% of the frame width from the left, and at the bottom).
* (int(width * 0.5), int(height * 0.5)) is the top-middle point of the triangle (center of the width, and 50% down from the top).
* (int(width * 0.9), height) is the bottom-right point of the triangle (90% of the frame width from the left, and at the bottom).
How to Adjust the Triangle:
Visually Inspect the Lane:

Run the program and see where the triangle is placed. 
1. Adjust the width * 0.1 and width * 0.9 values to move the triangle left or right.
2. Adjust height * 0.5 to raise or lower the top point of the triangle.

Define the HLD (Hough Line Detection)

In [1]:
def houghlines(img):
    hough_lines = cv.HoughLinesP(
        img,
        rho=6,  # Resolution of the accumulator in pixels
        theta=np.pi / 100,  # Angle resolution in radians
        threshold=150,  # Minimum number of intersecting points
        minLineLength=30,  # Minimum length of a line
        maxLineGap=10  # Maximum allowed gap between line segments
    )
    return hough_lines

# TRY THIS 

In [11]:
import numpy as np
import cv2 as  cv

# img = cv.imread('C:/Users/acer/Downloads/sudoku.png')
img = cv.imread('D:/Thinkin in programming/Metopen/Roi_img.jpg')
grays = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
blur = cv.GaussianBlur(grays, (5, 5),0)
edges = cv.Canny(blur, 30,100,apertureSize=3)

lines = cv.HoughLinesP(edges, 6, np.pi/80, threshold=100, minLineLength=40, maxLineGap=25)

for line in lines:
    x1,y1,x2,y2 = line[0]
    cv.line(img,(x1,y1),(x2,y2),(0,255,0),2)
# lines = cv.HoughLines(edges,1,np.pi/180,100)
# for rho,theta in lines[0]:
#     a = np.cos(theta)
#     b = np.sin(theta)
#     x0 = a*rho
#     y0 = b*rho
#     x1 = int(x0 + 1000 * (-b))
#     y1 = int(y0 + 1000 * (a))
#     x2 = int(x0 - 1000 * (-b))
#     y2 = int(y0 - 1000 * (a))

#     cv.line(img, (x1,y1), (x2,y2),(0,0,255),2)

cv.imshow("line",img)
cv.waitKey(0)
cv.destroyAllWindows()



with the following arguments:
* dst: Output of the edge detector. It should be a grayscale image (although in fact it is a binary one)
* lines: A vector that will store the parameters (r,θ) of the detected lines
* rho : The resolution of the parameter r in pixels. We use 1 pixel.
* theta: The resolution of the parameter θ in radians. We use 1 degree (CV_PI/180)
* threshold: The minimum number of intersections to "*detect*" a line
* srn and stn: Default parameters to zero. Check OpenCV reference for more info.

In [82]:
def make_points(img, lineSI, roi_bottom):
    slope, intercept = lineSI
    height = roi_bottom  # Use the bottom coordinate of the ROI
    y1 = int(height)  # Bottom of the ROI
    y2 = int(y1 * 1.5)  # Extend the line slightly beyond the bottom of the ROI

    # Calculate x coordinates based on slope and intercept
    x1 = int((y1 - intercept) / slope)
    x2 = int((y2 - intercept) / slope)

    return [[x1, y1, x2, y2]]  # Return the points in the format required by cv.line


# Before running this code below, you need to make sure that the line of the lane and the car
# is already correct. Specify the correct region of interest first
def average_slope_intercepts(img, lines, roi_bottom):
    left_fit = []
    right_fit = []
    
    for line in lines:
        for x1, y1, x2, y2 in line:
            # Check for a valid line length (avoid horizontal/vertical short lines)
            if abs(x2 - x1) > 0 and abs(y2 - y1) > 0:  
                fit = np.polyfit((x1, x2), (y1, y2), 1)
                slope = fit[0]
                intercept = fit[1]

                # Filter based on slope: negative for left, positive for right
                if slope < 0:  # Left lane
                    left_fit.append((slope, intercept))
                elif slope > 0:  # Right lane
                    right_fit.append((slope, intercept))

    # Average fits
    if left_fit:
        left_fit_average = np.average(left_fit, axis=0)
    else:
        left_fit_average = None

    if right_fit:
        right_fit_average = np.average(right_fit, axis=0)
    else:
        right_fit_average = None

    # Generate lines only if averages are available
    average_lines = []
    if left_fit_average is not None:
        left_line = make_points(img, left_fit_average, roi_bottom)
        average_lines.append(left_line)
    if right_fit_average is not None:
        right_line = make_points(img, right_fit_average, roi_bottom)
        average_lines.append(right_line)

    return average_lines


def display_lines_average(img, lines):
    line_image = [0]
    if lines is not None:
        for line in lines:
            for x1, y1, x2, y2 in line:
                cv.line(img, (x1,y1), (x2,y2), (0,0,255),10)
    return img
h_lines = houghlines(edges)

# Call the line function
roi_bottom = 300
avg_lines = average_slope_intercepts(img_cvt, h_lines, roi_bottom)
print(avg_lines)
print(h_lines)

lines_image = display_lines_average(img_cvt, avg_lines)
cv.imshow("Detected Lines", lines_image)
cv.waitKey(0)
cv.destroyAllWindows()

[[[490, 300, 385, 450]], [[517, 300, 679, 450]]]
[[[455 208 846 312]]

 [[500 209 752 244]]

 [[ 44  86 125 110]]

 ...

 [[226 225 256 222]]

 [[780 310 841 329]]

 [[790 249 827 254]]]


def average_slope_intercepts(img, lines):

sometimes(in most cases actually) it detects multiple lines.  to overcome this, we can use the average value within the lines as you’ve seen in this code.

bear in minds that, the lines (you can see at the ros function) is a lot of them. So you need to specify that only certain lines that is captured, hence it is called region of interest.

# Controlling the car

In [6]:
import time
import pyautogui as py
import pydirectinput

# Function to click at specified coordinates (using PyAutoGUI)
def click(x, y):
    py.click(x, y)  # Click at the specified coordinates
    time.sleep(0.5)  # Wait briefly to ensure the game is focused
    
def accelerate(hold_time):
    start = time.time()
    while time.time() - start < hold_time:
        pydirectinput.keyDown('up')
    pydirectinput.keyUp('up')

def turnLeft(hold_time):
    start = time.time()
    while time.time() - start < hold_time:
        pydirectinput.keyDown('a')
    pydirectinput.keyUp('a')

def turnRight(hold_time):
    start = time.time()
    while time.time() - start < hold_time:
        pydirectinput.keyDown('d')
    pydirectinput.keyUp('d')

# Accelerate for 10 seconds, then turn left and right
click(409, 275)
accelerate(10)
turnLeft(0.3)
turnRight(0.3)